In [ ]:
#import statements

In [1]:
import numpy as np

In [ ]:
# 1-a) Create an 1-d array named 'arr_int' of integers from 45 to 55 inclusive
# 1-b) Read back first 4 elements of 'arr_int'
# 1-c) Read back last element of 'arr_int'

In [2]:
# 1-a
arr_int = np.arange(45,56)
arr_int

array([45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55])

In [3]:
# 1-b
arr_int[0:4]

array([45, 46, 47, 48])

In [6]:
# 1-c
arr_int[-1]

55

In [ ]:
# 2-a) Create a 1-d array named 'arr_1' of 12 values from the random-normal distribution
# 2-b) Create a boolean array named ' arr_1_bool' which has "True" where the value in 'arr_1' is greater than 0.5
# 2-c) Reshape the 1-d array 'arr_1' to a 3 row, 4 column 2-d array called 'arr_2'

In [7]:
arr_1 = np.random.randn(12)
arr_1

array([-0.71524465,  0.06230861, -0.09655631,  0.10592079, -0.69921808,
        1.02121337,  2.10231849, -0.76999154, -0.54186686, -0.45252244,
       -0.77868968, -0.31851384])

In [8]:
arr_1_bool = arr_1 > 0.5
arr_1_bool

array([False, False, False, False, False,  True,  True, False, False,
       False, False, False])

In [9]:
arr_2 = arr_1.reshape(3,4)
arr_2

array([[-0.71524465,  0.06230861, -0.09655631,  0.10592079],
       [-0.69921808,  1.02121337,  2.10231849, -0.76999154],
       [-0.54186686, -0.45252244, -0.77868968, -0.31851384]])

In [ ]:
# 3-a) Add first 4 elements of 'arr_int' to first row of 'arr_2'. Store the result as 'arr_3'
# 3-b) Find the mean of 'arr_3'

In [10]:
arr_3 = arr_int[0:4] + arr_2[0]
arr_3

array([44.28475535, 46.06230861, 46.90344369, 48.10592079])

In [11]:
arr_3.mean()

46.3391071093614